version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: