version: "3"
services:
  app:
    container_name: chat_gpt_service
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    # depends_on:
    #   - db
#   db:
#     container_name: chat_gpt_service_db
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:
